### ISSUE TITLE
Fitting issue

### ISSUE THREAD

**Issue by mattiadutto** [abarcel/haikumodels#2]
I was trying to use a few of your pre-trained models, in particular the ResNet50 and VGG16 for features extraction, but unfortunately I didn't manage to fit on the Nvidia Titan X with 12GB of VRAM my question is which GPU did you use for training, how much VRAM I need for use them?

For the VGG16 the system was asking me for 4 more GB and for the ResNet50 about 20 more

Thanks.

**Comment by abarcel** [comment]
I used GTX 1080 ti with 11GB of VRAM while making this project and had no issue at that time.
I might need to revise the project as I didn't make any change in the last 8 months.
